config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: "users#new"
  root "static_pages#home"
  get '/help', to: "static_pages#help"
  get '/about', to: "static_pages#about"
  get '/contact', to: "static_pages#contact"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i # regex for email validation
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost:)
  end
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      redirect_to @user, status: :found, flash: { success: 'Welcome to the Hola!' }
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Hola App'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    reset_session
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Created by <%= link_to 'Basim Aljazaeri', "https://shiroyaksha90.github.io/"%>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path%></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Hola", root_path, id: "logo" %>
        <nav>
          <div class="navbar-header">
            <button id="hamburger" type="button" class="navbar-toggle collapsed">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
        <ul id="navbar-menu" class="nav navbar-nav navbar-right collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in?%>
              <li><%= link_to "Users", '#' %></li>
              <li class="dropdwon">
                <a href="#" id="account" class="dropdown-toggle">
                  Account
                  <b class="caret"></b>
                </a>
                <ul id="dropdown-menu" class="dropdown-menu">
                  <li><%= link_to "Profile", current_user%></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, data: {"turbo-method": :delete } %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/shim' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development?%>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation" >
        <div class="alert alert-danger" >
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<%provide(:title, 'About')%>
<h1>About Us</h1>

<p>Insert a brief description of your company or organization here.</p>

<h2>Our Team</h2>

<ul>
    <li>
        <h3>John Doe</h3>
        <p>Insert a brief bio of John Doe here.</p>
    </li>
    <li>
        <h3>Jane Smith</h3>
        <p>Insert a brief bio of Jane Smith here.</p>
    </li>
    <!-- Add more team members as needed -->
</ul>

<h2>Our Mission</h2>

<p>Insert a brief statement of your company or organization's mission here.</p>

<h2>Contact Us</h2>

<p>Insert your contact information here.</p>

app/views/static_pages/contact.html.erb
<%provide(:title, 'Contact')%>
<h1>Contact Us</h1>

<%= form_with url: contact_path, method: :post do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :email %>
    <%= form.email_field :email %>

    <%= form.label :message %>
    <%= form.text_area :message %>

    <%= form.submit "Send Message" %>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
    <h1>Help</h1>
    <p>Welcome to the help page. Here you can find answers to frequently asked questions and get assistance with any issues you may be experiencing.</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to our website!</h1>
    <%= link_to 'Sign up now!', signup_path, class: "btn btn-lg btn-primary"%>
    <p>Thank you for visiting our website. We hope you find what you're looking for.</p>
</div>

<%= link_to image_tag("social.webp", alt: "social logo"),
            "http://rubyonrails.org"%>

app/views/users/new.html.erb
<%provide(:title, 'Sign up')%>
<h1>Sign up</h1>
<div class="row">
    <div class="col-md-5 col-md-offset-3">
        <%= form_with(model: @user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %><%= f.text_field :name, class: 'form-control' %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.submit "Create my account", class: "btn btn-primary"
        %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user%>
                <%= @user.name%>
            </h1>
        </section>
    </aside>
</div>